var html = "";
	html += '<form class="w3-container">';
	html += '<div class="container">';
	html += '<div class="tophead-left column">';
	html += '<img src="img/hinh1.png">';
	html += '<h2><b>Hotline: <span><font color="#d80000">0964 299 222</font></span></b></h2>';
	html += '</div>';
	html += '<div class="tophead-midder column">';
	html += '<input type="text" placeholder="Tìm kiếm..." class="w3-input">';
	html += '<button type="submit" class="btn btn-timkiem btn-green">Tìm kiếm</button>';
	html += '</div>';
	html += '<div class="tophead-right">';
	html += '<a href="DangKy.html" class="btn btn-green dangky">';
	html += '<i class="fa fa-user-plus"></i>&nbsp; Đăng ký';
	html += '</a>';
	html += '<a href="DangNhap.html" class="btn btn-danger">';
	html += '<i class="fa fa-sign-in" aria-hidden="true"></i>Đăng nhập';
	html += '</a>';
	html += '</div>';
	html += '</div>';
	html += '</form>';
	var menu = '';
	menu += '<div class="container">';
	menu += '<div class="row">';
	menu += '<div class="menu-left column">';
	menu += '<ul class="ul_lef">';
	menu += '<li>Danh mục Khóa Học</li>';
	menu += '<li class="nav">';
	menu += '<a href=""><img src="img/tiengtrung.png"  class="logo_khoahoc">&nbsp; Khóa học Tiếng Trung</a>';
	menu += '<ul class="sub-menu">';
	menu += '<li><a href="GTHanNgu.html">Giáo Trình Hán Ngữ (Mới)</a></li>';
	menu += '<li><a href="GTBoya.html">Giáo Trình BoYa</a></li>';
	menu += '<li><a href="TiengTrungVanPhong.html">Tiếng Trung Văn Phòng</a></li>';
	menu += '</ul>';
	menu += '</li>';
	menu += '<li class="nav"><a href="KHTiengHan.html"><img src="img/tienghan.png"  class="logo_khoahoc">&nbsp; Khóa học Tiếng Hàn Quốc</a>';
	menu += '</li>';
	menu += '<li class="nav"><a href="KHTiengNhat.html"><img src="img/tiengnhat.png" class="logo_khoahoc">&nbsp; Khóa học Tiếng Nhật Bản</a></li>';
	menu += '</ul>';
	menu += '</div>';
	menu += '<div class="menu-right column">';
	menu += '<ul class="ul_right">';
	menu += '<li><a href="index.html">Trang chủ</a></li>';
	menu += '<li><a href="KM.html">khuyến mãi </a></li>';
	menu += '<li><a href="TinTuc.html">tin tức </a></li>';
	menu += '<li><a href="LienHe.html">liên hệ</a></li>';
	menu += '</ul>';
	menu += '<div class="slide">';
	menu += '<img src="img/slide1.jpg" class="slide_img">';
	menu += '</div>';
	menu += '</div>';
	menu += '</div>';
	menu += '</div>';

var footer = '';
footer += '<div class="container ">';
footer += '<div class="col-md-4">';
footer += '<h3><b>CÔNG TY CỔ PHẦN TƯ VẤN VÀ ĐÀO TẠO TOMATO</b></h3>';
footer += '<ul class="list-unstyled">';
footer += '<li><b>Địa chỉ ĐKKD:</b> CS1: Số 300 Lạch Tray, Quận. Lê Chân, Tp. Hải Phòng</li>';
footer += '<li><b>Cơ sở 2:</b> Số 65 Quán Nam, Quận, Lê Chân, Tp. Hải Phòng</li>';
footer += '<li><b>Cơ sở 3:</b> Số 148 Phan Đăng Lưu, Kiến An, Hải Phòng  ---  Cơ sở 4: 408 Trường Sơn, An Lão, Tp. Hải Phòng</li>';
footer += '<li><b>Điện thoại:</b> 0225 657 2222 - 0225 628 0123 - Support: (Zalo) 0965 113 913 Mr Nam</li>';
footer += '<li><b>Hotline:</b> 0964 299 222</li>';
footer += '<li><b>Email:</b> ngoaingutomatohp@gmail.com</li>';
footer += '</ul>';
footer += '<p>Website: http://tomatoonline.edu.vn&nbsp;- ngoaingutomato.edu.vn</p>';
footer += '<p>Giấy chứng nhận đầu tư số: 0201.636.998 do Sở Kế hoạch và Đầu tư TP Hải Phòng cấp ngày 10/06/2015</p>';
footer += '<p><a href="http://online.gov.vn/HomePage/CustomWebsiteDisplay.aspx?DocId=46630" rel="nofollow" target="_blank"><img alt="Thông báo bộ công thương Tomato" class="Thông Tomato báo bộ công thương" longdesc="Thông báo bộ công thương Tomato" src="http://tomatoonline.edu.vn/upload/images/dathongbao.png" style="height:65px; width:170px" title="Thông báo bộ công thương Tomato"></a></p>';
footer += '</div>';
footer += '<div class="col-md-4">';
footer += '<h3><b>THÔNG TIN TOMATO</b></h3>';
footer += '<ul class="list-unstyled">';
footer += '<li><a href="http://tomatoonline.edu.vn/huong-dan-nap-tien-p6.html">Hướng dẫn nạp tiền và thanh toán khoá học</a></li>';
footer += '<li><a href="http://tomatoonline.edu.vn/gioi-thieu-p2.html">Giới thiệu TOMATO</a></li>';
footer += '<li><a href="http://tomatoonline.edu.vn/dieu-khoan-su-dung-p15.html">Điều khoản sử dụng</a></li>';
footer += '<li><a href="http://tomatoonline.edu.vn/bao-mat-thong-tin-p14.html">Bảo mật thông tin</a></li>';
footer += '</ul>';
footer += '</div>';
footer += '<div class="col-md-4">';
footer += '<div class="fb-page fb_iframe_widget" data-href="https://www.facebook.com/tomatoonline.edu.vn/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="adapt_container_width=true&amp;app_id=141729702951631&amp;container_width=270&amp;hide_cover=false&amp;href=https%3A%2F%2Fwww.facebook.com%2Ftomatoonline.edu.vn%2F&amp;locale=vi_VN&amp;sdk=joey&amp;show_facepile=true&amp;small_header=false"><span style="vertical-align: bottom; width: 270px; height: 196px;"><iframe name="f387530fe5cd34c" width="1000px" height="1000px" title="fb:page Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v3.2/plugins/page.php?adapt_container_width=true&amp;app_id=141729702951631&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D45%23cb%3Df32d6afb4331534%26domain%3Dtomatoonline.edu.vn%26origin%3Dhttp%253A%252F%252Ftomatoonline.edu.vn%252Ff287908923a6398%26relation%3Dparent.parent&amp;container_width=270&amp;hide_cover=false&amp;href=https%3A%2F%2Fwww.facebook.com%2Ftomatoonline.edu.vn%2F&amp;locale=vi_VN&amp;sdk=joey&amp;show_facepile=true&amp;small_header=false" style="border: none; visibility: visible; width: 370px; height: 196px;" class=""></iframe></span></div>';
footer += '</div>';
footer += '</div>';
document.getElementById("tophead").innerHTML = html;
document.getElementById("block-2").innerHTML = menu;
document.getElementById("footer").innerHTML = footer;